apiVersion: storage.k8s.io/v1              # Specifies the API version (storage.k8s.io/v1) for the resource
kind: StorageClass                          # Defines the resource type as StorageClass
metadata:                                   # Metadata information about the StorageClass
  name: expense-ebs                         # Sets the name of the StorageClass to "expense-ebs"
reclaimPolicy: Retain                       # Specifies the reclaim policy as "Retain", meaning the storage will not be deleted automatically when released
provisioner: ebs.csi.aws.com                # Indicates the provisioner used for creating EBS volumes (AWS Elastic Block Store)
volumeBindingMode: WaitForFirstConsumer     # Sets the volume binding mode to "WaitForFirstConsumer", meaning the storage will be created only when a Pod that uses it is scheduled
